"""refactor roles permissions

Revision ID: 5ecf8b7099af
Revises: 80fb31265b8e
Create Date: 2026-02-13 14:38:37.590495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ecf8b7099af'
down_revision: Union[str, Sequence[str], None] = '80fb31265b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('member_permissions',
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], )
    )
    op.create_table('member_roles',
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    
    # --- Data Seeding ---
    permissions_table = sa.table('permissions',
        sa.Column('id', sa.Integer),
        sa.Column('name', sa.String),
        sa.Column('description', sa.String)
    )
    op.bulk_insert(permissions_table, [
        {'name': 'admin', 'description': 'Administrator'},
        {'name': 'member', 'description': 'Regular Member'},
        {'name': 'editor', 'description': 'Editor'},
    ])

    roles_table = sa.table('roles',
        sa.Column('id', sa.Integer),
        sa.Column('name', sa.String),
        sa.Column('description', sa.String)
    )
    op.bulk_insert(roles_table, [
        {'name': 'soprano', 'description': 'Soprano'},
        {'name': 'alto', 'description': 'Alto'},
        {'name': 'tenor', 'description': 'Tenor'},
        {'name': 'bass', 'description': 'Bass'},
        {'name': 'bass_guitar', 'description': 'Bass Guitar'},
        {'name': 'keyboard', 'description': 'Keyboard'},
        {'name': 'drums', 'description': 'Drums'},
        {'name': 'electric_guitar', 'description': 'Electric Guitar'},
    ])

    # --- Migrate Existing Data (PostgreSQL specific) ---
    # Migrate Roles from JSON to association table
    op.execute("""
        INSERT INTO member_roles (member_id, role_id)
        SELECT m.id, r.id
        FROM members m
        CROSS JOIN json_array_elements_text(m.roles) AS role_name
        JOIN roles r ON r.name = role_name
    """)
    
    # Migrate Permissions from JSON to association table
    op.execute("""
        INSERT INTO member_permissions (member_id, permission_id)
        SELECT m.id, p.id
        FROM members m
        CROSS JOIN json_array_elements_text(m.permissions) AS perm_name
        JOIN permissions p ON p.name = perm_name
    """)
    # ---------------------------------------------------
    op.drop_column('members', 'roles')
    op.drop_column('members', 'permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('roles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('member_roles')
    op.drop_table('member_permissions')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
