"""add_is_choir_role_to_role

Revision ID: 1ae0139242a9
Revises: c5ba3166407d
Create Date: 2026-03-31 22:20:43.588637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae0139242a9'
down_revision: Union[str, Sequence[str], None] = 'c5ba3166407d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_choir_role', sa.Boolean(), nullable=True, comment="Flag to identify roles used for choir scheduling slots (e.g. Soprano, Alto)."))
    
    # Seed choir roles
    op.execute(
        sa.text("INSERT INTO roles (name, is_choir_role) VALUES ('lead_singer', true), ('soprano', true), ('alto', true), ('tenor', true) "
                "ON CONFLICT (name) DO UPDATE SET is_choir_role = true")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_choir_role')
    # ### end Alembic commands ###
