"""remove_unique_constraint_on_assignments

Revision ID: a48e53a7ed08
Revises: f26d8038cc93
Create Date: 2026-04-03 05:38:59.639976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a48e53a7ed08'
down_revision: Union[str, Sequence[str], None] = 'f26d8038cc93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_session_role_assignment'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_session_role_assignment'), ['session_id', 'role'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
