"""add is_active and sunday lead singer

Revision ID: 09c39f49709f
Revises: a48e53a7ed08
Create Date: 2026-04-04 18:21:03.229258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c39f49709f'
down_revision: Union[str, Sequence[str], None] = 'a48e53a7ed08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        
    op.execute("UPDATE members SET is_active = true WHERE is_active IS NULL")
    
    # Insert new role
    op.execute(
        sa.text("INSERT INTO roles (name, is_choir_role) VALUES ('Sunday Lead Singer', false) "
                "ON CONFLICT (name) DO UPDATE SET is_choir_role = false")
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
