"""rename firstname lastname

Revision ID: a8892093c42d
Revises: 26a7eabe273c
Create Date: 2026-02-14 04:19:48.977700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8892093c42d'
down_revision: Union[str, Sequence[str], None] = '26a7eabe273c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'firstname', new_column_name='first_name')
    op.alter_column('members', 'lastname', new_column_name='last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'first_name', new_column_name='firstname')
    op.alter_column('members', 'last_name', new_column_name='lastname')
    # ### end Alembic commands ###
