"""replace_duration_with_end_time

Revision ID: d8da0f097abe
Revises: eeb504ebb1c3
Create Date: 2026-04-01 13:04:01.778065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8da0f097abe'
down_revision: Union[str, Sequence[str], None] = 'eeb504ebb1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))

    # Data migration: Set default end_time
    op.execute("UPDATE session_templates SET end_time = start_time + interval '2 hours' WHERE end_time IS NULL")
    op.execute("UPDATE sessions SET end_time = start_time + interval '2 hours' WHERE end_time IS NULL")

    with op.batch_alter_table('session_templates', schema=None) as batch_op:
        batch_op.alter_column('end_time', nullable=False)
        batch_op.drop_column('duration_minutes')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('end_time', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
        
    op.execute("UPDATE session_templates SET duration_minutes = EXTRACT(EPOCH FROM (end_time - start_time))/60 WHERE duration_minutes IS NULL")
    
    with op.batch_alter_table('session_templates', schema=None) as batch_op:
        batch_op.drop_column('end_time')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###
