"""add_frequency_to_session_template

Revision ID: eeb504ebb1c3
Revises: b5e13ade1ebe
Create Date: 2026-04-01 07:01:44.601615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb504ebb1c3'
down_revision: Union[str, Sequence[str], None] = 'b5e13ade1ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_templates', sa.Column('frequency', sa.String(), nullable=False))
    op.add_column('session_templates', sa.Column('reference_start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_templates', 'reference_start_date')
    op.drop_column('session_templates', 'frequency')
    # ### end Alembic commands ###
