"""add_device_id_and_location_to_models

Revision ID: 1c3e35712c3f
Revises: a8892093c42d
Create Date: 2026-02-19 04:15:52.506900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c3e35712c3f'
down_revision: Union[str, Sequence[str], None] = 'a8892093c42d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('device_id', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('radius', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'radius')
    op.drop_column('sessions', 'longitude')
    op.drop_column('sessions', 'latitude')
    op.drop_column('attendance', 'device_id')
    # ### end Alembic commands ###
