"""remove name column

Revision ID: 26a7eabe273c
Revises: 5ecf8b7099af
Create Date: 2026-02-13 14:46:22.534365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a7eabe273c'
down_revision: Union[str, Sequence[str], None] = '5ecf8b7099af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_name'), table_name='members')
    op.drop_column('members', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_members_name'), 'members', ['name'], unique=False)
    # ### end Alembic commands ###
