"""add_manager_permissions

Revision ID: 92f346574d1e
Revises: d8da0f097abe
Create Date: 2026-04-02 06:41:52.376057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92f346574d1e'
down_revision: Union[str, Sequence[str], None] = 'd8da0f097abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_templates', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIME(),
               nullable=True)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
               
    # Seed manager permissions
    permissions_table = sa.table('permissions',
        sa.Column('id', sa.Integer),
        sa.Column('name', sa.String),
        sa.Column('description', sa.String)
    )
    op.bulk_insert(permissions_table, [
        {'name': 'schedule_manager', 'description': 'Full access to calendar management, auto-generation, and templates.'},
        {'name': 'assignment_manager', 'description': 'Ability to modify member assignments for scheduled sessions.'},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove manager permissions
    op.execute("DELETE FROM permissions WHERE name IN ('schedule_manager', 'assignment_manager')")

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('session_templates', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###
