"""add google_refresh_token

Revision ID: c5ba3166407d
Revises: fdc450ccba5d
Create Date: 2026-03-30 00:57:58.610476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ba3166407d'
down_revision: Union[str, Sequence[str], None] = 'fdc450ccba5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('google_refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'google_refresh_token')
    # ### end Alembic commands ###
