"""add sync_token to members

Revision ID: dc8a58006655
Revises: 1a02e154503a
Create Date: 2026-03-21 22:43:09.075100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc8a58006655'
down_revision: Union[str, Sequence[str], None] = '1a02e154503a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('sync_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_members_sync_token'), 'members', ['sync_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_sync_token'), table_name='members')
    op.drop_column('members', 'sync_token')
    # ### end Alembic commands ###
