"""Add DayOff model

Revision ID: fdc450ccba5d
Revises: dc8a58006655
Create Date: 2026-03-29 04:59:09.484974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc450ccba5d'
down_revision: Union[str, Sequence[str], None] = 'dc8a58006655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_offs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'date', name='uq_member_date_day_off')
    )
    op.create_index(op.f('ix_day_offs_id'), 'day_offs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_day_offs_id'), table_name='day_offs')
    op.drop_table('day_offs')
    # ### end Alembic commands ###
